declare class Measurement {
    MeterID: number;
    MeterTypeID: number;
    MeterTypeCode: string;
    MeterTypeNameA: string;
    MeterTypeNameE: string;
    ProductName: string;
    MeterGroup: number;
    MeterGroupCode: string;
    MeterGroupNameA: string;
    MeterGroupNameE: string;
    MeterGroupDesc: string;
    LastNonZeroMeasureDate: Date;
    LastNonZeroMeasureTime: Date;
    LastNonZeroMeasureDateStr: string;
    LastNonZeroMeasureTimeStr: string;
    LastNonZeroMeasureUnit: string;
    LastNonZeroMeasureValue: number;
    LastNonZeroMeasureType: number;
    LastNonZeroMeasureTypeID: number;
    LastNonZeroMeasureTypeCode: string;
    LastNonZeroMeasureTypeNameA: string;
    LastNonZeroMeasureTypeNameE: string;
    LastMeasureDate: Date;
    LasMeasureTime: Date;
    LastMeasureDateStr: string;
    LasMeasureTimeStr: string;
    LastMeasureUnit: string;
    LastMeasureValue: number;
    LastMeasureType: number;
    LastMeasureTypeID: number;
    LastMeasureTypeCode: string;
    LastMeasureTypeNameA: string;
    LastMeasureTypeNameE: string;
    OnlineStatus: number;
    ValueStatus: boolean;
    GetRow(objBiz: Measurement): string;
}
declare function GetMeasurementInitialRow(vrMeasurement: Measurement, strBtns: string): string;
declare function ShowMeasurementModal(vrMeterID: number): void;
declare function DisplayMeasureRead(vrMeterID: number): void;
declare function DisplayLatestMeasureRead(): void;
declare function GetMeasurementLstTable(lstMeasurement: Measurement[]): string;
