declare class CheckSimple {
    ID: number;
    Direction: boolean;
    DirectionDesc: string;
    EditorName: string;
    BeneficiaryName: string;
    Bank: number;
    BankName: string;
    Code: string;
    CodeFrom: number;
    CodeTo: number;
    Type: number;
    TypeName: string;
    Value: number;
    CollectedValue: number;
    TotalPayment: number;
    Currency: number;
    CurrencyName: string;
    IssueDate: Date;
    DueDate: Date;
    DueDateMonthNo: number;
    PaymentDate: Date;
    Note: string;
    CurrentStatus: number;
    CurrentStatusDesc: string;
    ParentID: number;
    IsBankOriented: boolean;
    IsBankOrientedDesc: string;
    BankSubmissionDate: Date;
    Person: number;
    PersonType: number;
    GLAccount: number;
    Customer: number;
    CustomerName: string;
    Place: number;
    PlaceName: string;
    GetRow(objBiz: CheckSimple): string;
    GetNewCheckRow(vrIndex: number): string;
    FillSelectedTable(): string;
    AddCheckToSelected(intID: number): void;
    DeleteCheck(intIndex: number): void;
    GetCheckCopy(): CheckSimple;
    GetCheckLst(): CheckSimple[];
}
declare function CheckCheckValidation(): boolean;
declare function CheckCheckMultipleValidation(): boolean;
declare function GetPaymentCheckRow(intIndex: number, objBiz: CheckSimple): string;
declare function ReturnCheck(intIndex: number, strAllCheckLbl: string, strCheckLbl: string): void;
declare function FillPaymentCheckTable(): string;
declare function GetCheckSimpleMultiple(): CheckSimple;
declare function FillNewMultipleCheck(): void;
declare function FillMultipleCheckLst(arrCheck: CheckSimple[]): void;
declare function EditCheck(vrIndex: number): void;
declare function GetCheckInitialRow(vrCheck: CheckSimple, strBtns: string): string;
